services:
  db:
    image: mariadb:latest
    container_name: emp-db
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: emp
      MARIADB_DATABASE: emp
      MARIADB_USER: emp
      MARIADB_PASSWORD: emp